# Generated by Django 5.2.3 on 2025-08-25 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_administrator_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(max_length=50)),
                ('photo_attachment', models.FileField(upload_to='gallery/')),
                ('photo_description', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=50)),
                ('video_attachment', models.FileField(upload_to='gallery/')),
                ('video_description', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.visitor')),
            ],
        ),
    ]
