# Generated by Django 5.2.3 on 2025-08-24 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_author_slug_visitor_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_title', models.CharField(max_length=50)),
                ('memory_text', models.TextField()),
                ('memory_attachment', models.FileField(upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.visitor')),
            ],
        ),
    ]
