# Generated by Django 5.2.3 on 2025-11-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_article_abstract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_file',
            field=models.FileField(default='', upload_to='attachments/articles/files'),
        ),
    ]
