# Generated by Django 5.2.3 on 2026-02-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_main_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlegallery',
            name='article_picture',
            field=models.FileField(upload_to='attachments/articles/gallery'),
        ),
    ]
