# Generated by Django 5.2.3 on 2026-02-18 10:25

import apps.workshop.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('main_picture', models.ImageField(upload_to=apps.workshop.models.upload_workshop_image, verbose_name='تصویر اصلی')),
                ('workshop_date_time', models.DateTimeField(verbose_name='تاریخ و زمان برگزاری')),
                ('place', models.CharField(max_length=150, verbose_name='مکان برگزاری')),
                ('teacher', models.CharField(max_length=150, verbose_name='مدرس')),
                ('details', models.TextField(verbose_name='جزئیات کارگاه')),
                ('reg_guide', models.TextField(verbose_name='نحوه ثبت نام')),
                ('workshop_report', models.TextField(blank=True, null=True, verbose_name='گزارش کارگاه')),
                ('views', models.IntegerField(verbose_name='تعداد بازدید')),
                ('reg_date', models.DateField(verbose_name='تاریخ ثبت')),
                ('is_active', models.BooleanField(verbose_name='وضعیت فعالیت')),
            ],
            options={
                'verbose_name': 'کارگاه',
                'verbose_name_plural': 'کارگاه ها',
            },
        ),
        migrations.CreateModel(
            name='WorkshopStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_title', models.CharField(max_length=100, verbose_name='وضعیت کارگاه')),
            ],
            options={
                'verbose_name': 'وضعیت کارگاه',
                'verbose_name_plural': 'وضعیت ها',
            },
        ),
        migrations.CreateModel(
            name='WorkshopGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=apps.workshop.models.upload_workshop_gallery)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop', verbose_name='کارگاه')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری ها',
            },
        ),
        migrations.AddField(
            model_name='workshop',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshopstatus', verbose_name='وضعیت کارگاه'),
        ),
    ]
