# Generated by Django 5.2.3 on 2025-09-10 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_family', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=40)),
                ('message_title', models.CharField(max_length=30)),
                ('message_text', models.TextField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VisitDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='VisitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_title', models.CharField(max_length=20)),
                ('rule_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_title', models.CharField(max_length=30)),
                ('place_picture', models.FileField(upload_to='attachments/articles')),
                ('visit_time', models.TimeField()),
                ('description', models.TextField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('visit_day', models.ManyToManyField(to='about.visitday')),
                ('visit_rules', models.ManyToManyField(to='about.visitrule')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.place')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.visitorgroup')),
            ],
        ),
    ]
