# Generated by Django 5.2.3 on 2025-09-12 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='place_part',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='about.part'),
        ),
    ]
