# Generated by Django 5.2.3 on 2025-09-12 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_part_place_place_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.part'),
        ),
    ]
