# Generated by Django 5.2.3 on 2025-09-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_place_place_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='ticket_required',
            field=models.BooleanField(default=False),
        ),
    ]
