# Generated by Django 5.2.3 on 2025-09-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_place_ticket_required'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
