# Generated by Django 5.2.3 on 2025-08-25 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_administrator_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('ticket_price', models.IntegerField()),
                ('visit_day', models.CharField(max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.staff')),
            ],
        ),
    ]
