# Generated by Django 5.2.3 on 2025-09-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_family', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=40)),
                ('message_title', models.CharField(max_length=30)),
                ('message_text', models.TextField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
            ],
        ),
    ]
