# Generated by Django 5.2.3 on 2025-11-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='نام کابر')),
                ('user_family', models.CharField(max_length=20, verbose_name='نام خانوادگی کابر')),
                ('user_email', models.EmailField(max_length=40, verbose_name='ایمیل')),
                ('message_title', models.CharField(max_length=30, verbose_name='عنوان پیام')),
                ('message_text', models.TextField(verbose_name='متن پیام')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
            ],
        ),
    ]
