# Generated by Django 5.2.3 on 2025-09-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_title',
            field=models.CharField(max_length=30, verbose_name='عنوان پیام'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_email',
            field=models.EmailField(max_length=40, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_family',
            field=models.CharField(max_length=20, verbose_name='نام خانوادگی کابر'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name='نام کابر'),
        ),
    ]
