# Generated by Django 5.2.3 on 2025-08-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='', max_length=55, unique=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='slug',
            field=models.SlugField(default='', max_length=55, unique=True),
        ),
    ]
