# Generated by Django 6.0.5 on 2026-07-17 19:17

import apps.memories.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_title', models.CharField(max_length=150)),
                ('memory_text', models.TextField()),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('user_registered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Memories',
            },
        ),
        migrations.CreateModel(
            name='MemoryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_image', models.ImageField(upload_to=apps.memories.models.upload_gallery_image)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='memories.memory')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='memories.memory')),
                ('user_liked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
